#!/usr/bin/env bash                                                  
# A bash script that diplays the PID of my Bash process              
# shellcheck disable=SC2009                                          
ps -auxf | grep bash
